### ISSUE TITLE
GPT error

### ISSUE THREAD

**Issue by periplume** [abeleinin/goki#10]
Project looks interesting. However, running the GPT function throws the following error:

```
panic: runtime error: index out of range [0] with length 0                                       

goroutine 98 [running]:
main.gptClient({0xc000110790, 0xd})
	/home/jason/go/pkg/mod/github.com/abeleinin/goki@v0.0.0-20240526032438-9653b1a4e4ff/gpt.go:113 +0xdbc
main.asyncGpt(0xc000185308, {0xc000110790?, 0xc0002960a8?})
	/home/jason/go/pkg/mod/github.com/abeleinin/goki@v0.0.0-20240526032438-9653b1a4e4ff/model.go:67 +0x30
created by main.(*User).Update in goroutine 1
	/home/jason/go/pkg/mod/github.com/abeleinin/goki@v0.0.0-20240526032438-9653b1a4e4ff/model.go:169 +0x311f

```
which in turn appears to leave the terminal in an unusable state (stty -echo among others are set and then not unset after the panic). it also leaves the json config files in .local/share/goki corrupted, which prevents it from starting until it is removed:

**go: go version go1.22.2 linux/amd64
os: ubuntu 24.04.1**

**Comment by abeleinin** [comment]
Thanks for submitting this issue! It looks like I wasn't doing proper error handling from the api response. Just double check that you set the environment variable `OPENAI_API_KEY` to a valid key from your [openai account](https://platform.openai.com/api-keys), and the generation should work. Feel free to reopen or submit more issues if you run into any!
