### ISSUE TITLE
Feature request: CSV import

### ISSUE THREAD

**Issue by BNolet** [abeleinin/goki#2]
It would be super cool to be able to import a CSV and use that to populate a deck

**Comment by indigomarxist** [comment]
Would love to see this, would make it far easier to switch over from Anki.

**Comment by abeleinin** [comment]
Great idea! Working on it now.

**Comment by abeleinin** [comment]
I hope you enjoy! Let me know if you have any other feature requests or find any bugs.

**Comment by BNolet** [comment]
This is awesome! Thank you for this :D

The only bug I found was due to Numbers on macOS being weird and introducing extra empty csv columns. 

Goki caught that there was an issue but ended off the import with "import successful"

As well, I would suggest putting a check for existing deck names when importing. Just letting the user know "hey there's another deck with that name already, are you sure you want to import?" would be sufficient in my opinion

**Comment by abeleinin** [comment]
Ok, thanks for letting me know!
