### ISSUE TITLE
Entering an empty name should not complete the name change

### ISSUE THREAD

**Issue by itsmexxie** [abeleinin/goki#3]
Pressing enter on an empty string while editing a deck's name should not complete the name change in my opinion. It should either stay with the same name as before or not let the user confirm.

**Comment by abeleinin** [comment]
Thank you for sharing. Working on it now.

**Comment by abeleinin** [comment]
Run the following to update.
```
go get -u github.com/abeleinin/goki 
```
 Let me know if you have any other feature requests or bug fixes!
