### ISSUE TITLE
CSV import bug

### ISSUE THREAD

**Issue by jonahfried** [abeleinin/goki#6]
https://github.com/abeleinin/goki/blob/8257248e9f447650f10638867fc1538119a5bde7/main.go#L50C2-L51C2

Hey! 

There's a small bug with CSV importing. You seem to only consider the first arg so if you do `goki -n "my name" -t < anki_import.txt` it won't parse correctly (but say import successful), because the sep doesn't get set to \t.

**Comment by abeleinin** [comment]
Fixed the exit to tui bug when reviewing in the cli
